#!/usr/bin/env bun
/**
 * Builds the amc binary with `bun build --compile`, UI and pixel assets inside.
 *
 *   bun apps/cli/build.ts                 # this platform -> dist/amc
 *   bun apps/cli/build.ts --all           # dist/amc-<os>-<arch> for every RELEASE_TARGETS entry
 *   bun apps/cli/build.ts --target bun-linux-x64 [--outfile dist/amc-linux]
 *
 * Needs apps/web/dist (task build:bin builds it first). Embedding works by
 * generating a module that imports every UI file `with { type: "file" }` (Bun
 * puts those in the binary and hands back a /$bunfs path) and swapping it in
 * for src/web-assets.ts at resolve time. Bun 1.3 has no directory --asset flag,
 * and this keeps the checkout's stub module untouched.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dir, "../..");
const WEB_DIST = path.join(ROOT, "apps/web/dist");
const OUT_DIR = path.join(ROOT, "dist");
const GEN_DIR = path.join(OUT_DIR, ".amc-build");

export const RELEASE_TARGETS = [
  "bun-darwin-arm64",
  "bun-darwin-x64",
  "bun-linux-x64",
  "bun-linux-arm64",
] as const;

/** Every file the UI needs, as URL path -> absolute path. The pixel-art sources (_src) stay out. */
export function listWebFiles(dist: string): Record<string, string> {
  const out: Record<string, string> = {};
  const walk = (dir: string) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, e.name);
      if (e.isDirectory()) {
        if (e.name !== "_src") walk(abs);
      } else if (e.isFile() && !e.name.endsWith(".ts") && e.name !== ".DS_Store") {
        out[`/${path.relative(dist, abs).split(path.sep).join("/")}`] = abs;
      }
    }
  };
  walk(dist);
  return out;
}

export function manifestSource(files: Record<string, string>): string {
  const entries = Object.entries(files).sort(([a], [b]) => a.localeCompare(b));
  const imports = entries.map(
    ([, abs], i) => `import f${i} from ${JSON.stringify(abs)} with { type: "file" };`,
  );
  const map = entries.map(([url], i) => `  ${JSON.stringify(url)}: f${i},`);
  return `// Generated by apps/cli/build.ts. Do not edit.\n${imports.join("\n")}\n\nexport const webAssets: Record<string, string> = {\n${map.join("\n")}\n};\n`;
}

async function buildOne(target: string | undefined, outfile: string, manifest: string) {
  const result = await Bun.build({
    entrypoints: [path.join(import.meta.dir, "src/main.ts")],
    compile: target ? { target: target as Bun.Build.CompileTarget, outfile } : { outfile },
    minify: { syntax: true, whitespace: true },
    plugins: [
      {
        name: "embed-web-assets",
        setup(b) {
          b.onResolve({ filter: /^\.\/web-assets$/ }, () => ({ path: manifest }));
        },
      },
    ],
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error(`build failed for ${target ?? "this platform"}`);
  }
  console.log(`built ${path.relative(ROOT, outfile)}${target ? ` (${target})` : ""}`);
}

if (import.meta.main) {
  const argv = process.argv.slice(2);
  const val = (name: string) => {
    const i = argv.indexOf(name);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  if (!fs.existsSync(path.join(WEB_DIST, "index.html"))) {
    console.error("apps/web/dist is missing: run `task build` first (task build:bin does).");
    process.exit(1);
  }
  const files = listWebFiles(WEB_DIST);
  fs.mkdirSync(GEN_DIR, { recursive: true });
  const manifest = path.join(GEN_DIR, "web-assets.ts");
  fs.writeFileSync(manifest, manifestSource(files));
  console.log(`embedding ${Object.keys(files).length} UI files`);

  if (argv.includes("--all")) {
    for (const t of RELEASE_TARGETS) {
      await buildOne(t, path.join(OUT_DIR, `amc-${t.replace(/^bun-/, "")}`), manifest);
    }
  } else {
    const target = val("--target");
    await buildOne(target, path.resolve(val("--outfile") ?? path.join(OUT_DIR, "amc")), manifest);
  }
}
